---

- hosts: all
  gather_facts: no
  pre_tasks:
    - name: apt-get update
      apt: update_cache=yes
      become: yes
      ignore_errors: true

    - name: install python2
      raw: test -e /usr/bin/python || sudo apt-get -y install python-minimal
      become: yes

- hosts: puppet_nodes
  gather_facts: yes
  become: yes
  roles:
    - {role: test,
       debug: ["{{debug}}"]}
