# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'
conf = {}
conf_path = ENV.fetch("USER_CONF","config.yml")
if File.file?(conf_path)
    user_conf = YAML.load_file(File.join(File.dirname(__FILE__),conf_path))
    conf.update(user_conf)
else
    raise "Configuration file #{conf_path} does not exist."
end

Vagrant.configure("2") do |config|
  config.vm.box = conf['box_name']
  config.vm.box_check_update = false
  config.vm.box_url = conf['box_url'] if conf['box_url']
  config.vm.box_version = conf['box_version'] if conf['box_version']
  config.vm.hostname = conf['box_hostname']

  # config.ssh.username = vagrant

  # resolve "stdin: is not a tty warning", related issue and proposed
  # fix: https://github.com/mitchellh/vagrant/issues/1673
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  config.ssh.forward_agent = true

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "private_network", ip: "192.168.1.10", :netmask => "255.255.255.0", :auto_config => false
  # config.vm.network "public_network"

  if conf['local_sync_folder']
	config.vm.synced_folder conf['local_sync_folder'], "/vagrant"
  end
	
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.customize ["modifyvm", :id, "--cpus", conf['cpus']]
    vb.customize ["modifyvm", :id, "--memory", conf['memory']]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]

    # change the network card hardware for better performance
    vb.customize ["modifyvm", :id, "--nictype1", "virtio" ]
    vb.customize ["modifyvm", :id, "--nictype2", "virtio" ]

    # suggested fix for slow network performance
    # see https://github.com/mitchellh/vagrant/issues/1807
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
  

  
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
