heat_template_version: 2015-04-30
description: Create a minimal infrastructure to spawn an instance
parameters:
  external_network_id:
    type: string
    label: External network id
    description: External network to connect the router
    default: cd3de404-0cfc-4cc2-88c9-bdeff3733094

resources:
  my-net:
    type: OS::Neutron::Net
    properties:
      name: my-net

  my-subnet:
    type: OS::Neutron::Subnet
    properties:
      name: my-subnet
      network_id: { get_resource: my-net }
      cidr: 192.168.8.0/24
      dns_nameservers: [8.8.8.8, 8.8.4.4]
      ip_version: 4
      allocation_pools:
        - { start: 192.168.8.2, end: 192.168.8.250 }

  my-router:
    type: OS::Neutron::Router
    properties:
      name: my-router

  my-router-gateway:
    type: OS::Neutron::RouterGateway
    properties:
      router_id: { get_resource: my-router }
      network_id: { get_param: external_network_id }

  my-router-subnet-int:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: my-router }
      subnet_id: { get_resource: my-subnet }

  my-security-group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: my-sg
      description: Add security group rules for server
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          direction: ingress
        - remote_ip_prefix: 0.0.0.0/0
          direction: egress

